routes/web.php
<?php

use App\Http\Controllers\ProfileController;
use Illuminate\Support\Facades\Route;
use App\Http\Controllers\RoleController;
use App\Http\Controllers\StudentController;
use App\Http\Controllers\BatchController;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider and all of them will
| be assigned to the "web" middleware group. Make something great!
|
*/

Route::view('test', 'test');
Route::post('test', function(){
    dd($_POST);
});

Route::get('/', function () {
    return view('welcome');
});


    Route::get('/batches', [BatchController::class, 'index'])->name('batches.index');
    Route::get('/batches/create', [BatchController::class, 'create'])->name('batches.create');
    Route::post('/batches/store', [BatchController::class, 'store'])->name('batches.store');
    Route::get('/batches/{batch}/show', [BatchController::class, 'show'])->name('batches.show');
    Route::get('/batches/{batch}/edit', [BatchController::class, 'edit'])->name('batches.edit');
    Route::patch('/batches/{batch}/update', [BatchController::class, 'update'])->name('batches.update');
    Route::delete('/batches/{batch}', [BatchController::class, 'destroy'])->name('batches.delete');
    
    Route::get('/students', [StudentController::class, 'index'])->name('students.index');
    Route::get('/students/create', [StudentController::class, 'create'])->name('students.create');
    Route::post('/students/store', [StudentController::class, 'store'])->name('students.store');
    Route::get('/students/{student}/show', [StudentController::class, 'show'])->name('students.show');
    Route::get('/students/{student}/edit', [StudentController::class, 'edit'])->name('students.edit');
    Route::patch('/students/{student}/update', [StudentController::class, 'update'])->name('students.update');
    Route::delete('/students/{student}', [StudentController::class, 'destroy'])->name('students.delete');


Route::get('/dashboard', function () {
    return view('backend.dashboard');
})->middleware(['auth', 'verified'])->name('dashboard');

Route::middleware('auth')->group(function () {
    Route::get('/profile', [ProfileController::class, 'edit'])->name('profile.edit');
    Route::patch('/profile', [ProfileController::class, 'update'])->name('profile.update');
    Route::delete('/profile', [ProfileController::class, 'destroy'])->name('profile.destroy');




    Route::group(['prefix'=>'roles','as'=>'roles.'], function(){
        Route::get('/', [RoleController::class, 'index'])->name('index');
        Route::get('/create', [RoleController::class, 'create'])->name('create');
        Route::post('/store', [RoleController::class, 'store'])->name('store');
        Route::get('/show/{role}', [RoleController::class, 'show'])->name('show');
        Route::get('/{role}/edit', [RoleController::class, 'edit'])->name('edit');
        Route::patch('/{role}', [RoleController::class, 'update'])->name('update');
    });

    



});

require __DIR__.'/auth.php';

app/Models/Role.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

class Role extends Model
{
    use HasFactory;

    protected $fillable = [
        'role_name',
    ];
}

app/Http/Controllers/RoleController.php
<?php

namespace App\Http\Controllers;

use App\Models\Role;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\DB;

class RoleController extends Controller
{
    public function index()
    {
        $roles = Role::get();
        return view('backend.roles.index', compact('roles'));
    }

    public function create()
    {
        return view('backend.roles.create');
    }

    public function store(Request $request)
    {
        // dd($request->all());
        Role::create([
            'role_name' => $request->role_name
        ]);
        return redirect()->route('roles.index');
    }

    public function show(Role $role)
    {
        return view('backend.roles.show', compact('role'));
    }

    public function edit(Role $role)
    {
        return view('backend.roles.edit', compact('role'));
    }

    public function update(Request $request, Role $role)
    {
        $role->update([
            'role_name' => $request->role_name
        ]);
        return redirect()->route('roles.index');
    }

    public function destroy(Role $role)
    {
        //
    }
}

resources/views/backend/roles/create.blade.php
<x-backend.layouts.master>
    <form action="{{ route('roles.store')}}" method="POST">
        @CSRF
        <label for="role_name">Role Name</label>
        <input type="text" name="role_name">
        <button type="submit">Save</button>
    </form>
</x-backend.layouts.master>

resources/views/backend/roles/edit.blade.php
<x-backend.layouts.master>
    <form action="{{ route('roles.update', $role->id)}}" method="POST">
        @CSRF
        @method('PATCH')
        <label for="role_name">Role Name</label>
        <input type="text" name="role_name" value="{{$role->role_name}}">
        <button type="submit">Save</button>
    </form>
</x-backend.layouts.master>

resources/views/backend/roles/index.blade.php
<x-backend.layouts.master>
    <table style="width: 100%; border-collapse: collapse" border="1">
        <thead>
            <tr>
                <th colspan="3"><h3>Role</h3></th>
            </tr>
            <tr>
                <th colspan="3" style="text-align: right">
                    <button><a href="{{ route('roles.create')}}">Add New Role</a></button>
                </th>
            </tr>
            <tr>
                <th>Ser No</th>
                <th>Role Name</th>
                <th>Action</th>
            </tr>
        </thead>
        <tbody>
            @php
                $sl=1
            @endphp
            @foreach ($roles as $role)
            <tr>
                <td>{{$sl++}}</td>
                <td>{{$role->role_name}}</td>
                <td>
                    <a href="{{ route('roles.show', $role->id)}}">Show</a>
                    <a href="{{ route('roles.edit', $role->id)}}">Edit</a>
                    <button>Delete</button>
                </td>
            </tr>
            @endforeach
        </tbody>
    </table>
</x-backend.layouts.master>

resources/views/backend/roles/show.blade.php
<x-backend.layouts.master>
    Role Name: {{$role->role_name}}
    <button><a href="{{route('roles.index')}}">Back</a></button>
</x-backend.layouts.master>